[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 3000

# Servir arquivos estáticos diretamente
[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Servir favicon
[[redirects]]
  from = "/favicon.ico"
  to = "/.netlify/functions/simple/favicon.ico"
  status = 200

# Redirect remaining routes to Netlify function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/simple/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Headers for favicon
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=86400"