services:
  - type: web
    name: z3z-blog
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    scaling:
      minInstances: 1
      maxInstances: 1